version: '2'
services:
  web:
    build: .
    command: bundle exec rackup -o '0.0.0.0' -p 3000
    volumes:
      - "./data:/ganoff.tk/data/db-production.sqlite3"
    ports:
      - "60001:3000"
    environment:
      - RACK_ENV=production
